---
framework: jest
licenseTier: small
preRun:
     command:
        - npm i
preMerge:
  pattern:
    - './src/api/forms.spec.ts'
postMerge: 
  pattern: 
    - './src/api/forms.spec.ts'
postRun:
     command:
        - node --version
version: 1.0
